# -*- coding: utf-8 -*-
"""22201403_Md. Khairul Ashik_CSE427Lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I6OyXSsaXufyEwiw1HOvOlzM6vmB-kRa

# Numpy Tasks
"""

import numpy as np

"""T-1"""

a=np.random.randint(1,101,20)
b=np.random.randint(1,101,20)
print(a)
print(b)

"""T-2"""

a_matrix= a.reshape(5,4)
b_matrix= b.reshape(5,4)

print(a_matrix)
print(b_matrix)

"""T-3"""

print(a_matrix*b_matrix)

"""T-4"""

b_matrix_upd=b_matrix.T
c=np.matmul(a_matrix,b_matrix_upd)
print(c)

"""T-5"""

c_partial= c[:,1:3]
print(c_partial)

print(c[:,:])

"""T-6"""

maxm_value= np.max(c)
print(maxm_value)

index= np.argmax(c)
print(index)

"""T-7"""

one_dimentional_array=c_partial.flatten()
one_dimentional_array

"""# Pandas Tasks"""

import pandas as pd

"""T-1"""

loc = "/content/subject_scores.csv"
df = pd.read_csv(loc)
print(df)

"""T-2"""

df.head(10)

"""T-3"""

df.info()

"""T-4"""

df.isnull().sum()

"""T-5"""

df["Math"] = df["Math"].fillna(df["Math"].mean())
df

"""T-6"""

math_scores = df["Math"]
math_scores

"""# Matplotlib Tasks"""

import matplotlib.pyplot as plt

"""T-1"""

temperature_dhaka =np.array([25,34,21,45,28,6,43,18,7,2])
humidity_dhaka =np.array([28, 25,29,20, 26, 50, 19, 29, 52, 55])
plt.xlabel("temperature_dhaka")
plt.ylabel("humidity_dhaka")
plt.title("temperature_dhaka vs humidity_dhaka")
plt.scatter(temperature_dhaka, humidity_dhaka, marker ="*",color ="r")
plt.show()

"""T-2"""

study_hours =np.array([2,3,4,4, 5, 6, 7, 7, 8, 9, 9, 10, 11, 11, 12])
marks =np.array([6, 10, 15, 20, 34, 44, 55, 60, 55, 67, 70, 80, 90, 99, 100])
plt.figure(figsize=(12,8))
plt.xlabel("study_hours")
plt.ylabel("marks")
plt.title("study_hours vs marks")
plt.plot(study_hours,marks,color ="g")
plt.show()

"""T-3"""

subjects = np.array(['Maths', 'English', 'Science', 'Physics', 'Computer'])
marks = np.array([89, 90, 45, 78, 99])

plt.figure(figsize=(10, 6))
plt.barh(subjects, marks)
plt.xlabel("Marks")
plt.ylabel("Subjects")
plt.title("Scores in Each Subject")
plt.xlim(0, 100)
plt.grid(axis="x")
plt.show()

"""T-4"""

import matplotlib.pyplot as plt
import numpy as np

subjects = np.array(['Maths', 'English', 'Science', 'Physics', 'Computer'])
marks = np.array([89, 90, 45, 78, 99])
colors = ["r","g","b","y","pink"]
plt.figure(figsize=(10, 6))
plt.bar(subjects,marks, color= colors)
plt.xlabel("Subjects")
plt.ylabel("Marks")
plt.title("Scores in Each Subject")
plt.ylim(0, 100)
plt.grid(axis="y")
plt.show()

"""T-5"""

temperature_dhaka = np.array([25,34,21,45,28,6,43,18,7,2])
humidity_dhaka = np.array([28, 25,29,20, 26, 50, 19, 29, 52, 55])


study_hours = np.array([2,3,4,4, 5, 6, 7, 7, 8, 9, 9, 10, 11, 11, 12])
marks_for_study_hours  = np.array([6, 10, 15, 20, 34, 44, 55, 60, 55, 67, 70, 80, 90, 99, 100])


subjects = np.array(['Maths', 'English', 'Science', 'Physics', 'Computer'])
marks_for_subjects = np.array([89, 90, 45, 78, 99])
colors = ["r","g","b","y","pink"]

fig = plt.figure(figsize=(15,10))

y1 = fig.add_subplot(2,2,1)
y1.scatter(temperature_dhaka, humidity_dhaka,marker = "*",color ="r")
y1.set_xlabel("Temperature")
y1.set_ylabel("Humidity")
y1.set_title("temperature_dhaka vs humidity_dhaka")

y2 = fig.add_subplot(2,2,2)
y2.plot(study_hours, marks_for_study_hours, color ="g")
y2.set_xlabel("Study Hours")
y2.set_ylabel("Marks")
y2.set_title("study_hours vs marks")

y3 = fig.add_subplot(2,2,3)
y3.barh(subjects, marks_for_subjects)
y3.set_xlabel("Marks")
y3.set_ylabel("Subjects")
y3.set_title("Scores in Each Subject(Horizontal)")
y3.set_xlim(0,100)
y3.grid(axis="x")


y4 = fig.add_subplot(2, 2, 4)
y4.bar(subjects,marks_for_subjects, color= colors)
y4.set_xlabel("Subjects")
y4.set_ylabel("Marks")
y4.set_title("Scores in Each Subject (Vertical)")
y4.set_ylim(0,100)
y4.grid(axis="y")
plt.show()